CREATE DATABASE admin_db;
GRANT ALL PRIVILEGES ON admin_db.* TO 'laravel_user'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE test_db;
GRANT ALL PRIVILEGES ON test_db.* TO 'laravel_user'@'%';
FLUSH PRIVILEGES;